import type { Metadata } from "next";

import Link from "next/link";

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "1fr 400px",
        gap: 68,
        padding: 26,
      }}
    >
      {children}
      <nav>
        <p>
          <Link href="/lang">lang</Link>
        </p>
        <p>
          <Link href="/lang/lang-attr">lang/lang-attr</Link>
        </p>
      </nav>
    </div>
  );
}
